eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8888
spring:
    application:
        name: config-cloud
    profiles:
        active: native
    cloud:
        config:
            server:
                # 本地方式配置文件
                native:
                    search-locations: classpath:/configs
                # git方式配置文件
#                git:
#                    uri: https://github.com/LowKeyZC/bm-cloud
#                    search-paths: configs