eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8888
spring:
    application:
        name: config-cloud
    cloud:
        config:
            server:
              git:
                uri: https://github.com/LowKeyZC/bm-cloud
                search-paths: config-file