#服务端口号
server:
    port: 8762
#注册中心
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
spring:
    #数据源
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        name: webstu
        url: jdbc:mysql://127.0.0.1:3306/webstu?characterEncoding=utf-8&useSSL=true
        username: root
        password: 123456
    #链路追踪
    zipkin:
        base-url: http://localhost:9411
    #配置采样百分比
    sleuth:
        sampler:
            probability: 1
#mybatis
mybatis:
    mapper-locations: "classpath:mapper/*.xml"
    config-location: "classpath:mybatis-config.xml"